version: '3.1'

services:
  app:
    image: loctvl842/ucook-api
    container_name: ucook-api
    build: .
    ports:
      - 8402:8402
    tty: true
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASS=thangcho
      - DB_NAME=ucook
      - DB_PORT=5432
      - DB_TYPE=postgres
    command: make run-server
    networks:
      - postgres-network
    volumes:
      - .:/app
  postgres:
    image: postgres
    container_name: ucook-postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    hostname: database
    environment:
      POSTGRES_PASSWORD: thangcho
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  postgres-network:
    driver: bridge
    name: postgres-network

volumes:
  pgdata:
    name: pgdata
